version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.1.0
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - checkout
      - run:
          name: build container
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
workflows:
  scan_image:
    jobs:
      - local_image_scan
